# Form implementation generated from reading ui file 'agenda.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Agenda(object):
    def setupUi(self, Agenda):
        Agenda.setObjectName("Agenda")
        Agenda.resize(356, 309)
        Agenda.setMaximumSize(QtCore.QSize(356, 309))
        Agenda.setStyleSheet("background-color: rgb(122, 122, 122);\n"
"color: rgb(6, 6, 6);")
        self.centralwidget = QtWidgets.QWidget(parent=Agenda)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("QLabel{\n"
"    border-radius:5px;\n"
"    background-color: rgb(213, 213, 213);\n"
"    font: 14pt \"Times New Roman\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"    \n"
"    font: 14pt \"Times New Roman\";\n"
"    background-color: rgb(204, 204, 204);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(79, 79, 79);\n"
"    font: 75 15pt \"Times New Roman\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(68, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(68, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(68, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 6, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(68, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 7, 0, 1, 1)
        self.btn_buscar = QtWidgets.QPushButton(parent=self.frame)
        self.btn_buscar.setObjectName("btn_buscar")
        self.gridLayout_2.addWidget(self.btn_buscar, 8, 0, 1, 1)
        self.btn_salvar = QtWidgets.QPushButton(parent=self.frame)
        self.btn_salvar.setObjectName("btn_salvar")
        self.gridLayout_2.addWidget(self.btn_salvar, 8, 1, 1, 2)
        self.btn_deletar = QtWidgets.QPushButton(parent=self.frame)
        self.btn_deletar.setObjectName("btn_deletar")
        self.gridLayout_2.addWidget(self.btn_deletar, 8, 3, 1, 1)
        self.btn_limpar = QtWidgets.QPushButton(parent=self.frame)
        self.btn_limpar.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btn_limpar.setObjectName("btn_limpar")
        self.gridLayout_2.addWidget(self.btn_limpar, 8, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(68, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 70))
        self.label.setStyleSheet("font: 22pt \"Times New Roman\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 5)
        self.ln_contato = QtWidgets.QLineEdit(parent=self.frame)
        self.ln_contato.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ln_contato.setObjectName("ln_contato")
        self.gridLayout_2.addWidget(self.ln_contato, 2, 2, 1, 3)
        self.ln_fone = QtWidgets.QLineEdit(parent=self.frame)
        self.ln_fone.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ln_fone.setObjectName("ln_fone")
        self.gridLayout_2.addWidget(self.ln_fone, 4, 2, 1, 3)
        self.ln_email = QtWidgets.QLineEdit(parent=self.frame)
        self.ln_email.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ln_email.setObjectName("ln_email")
        self.gridLayout_2.addWidget(self.ln_email, 6, 2, 1, 3)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        Agenda.setCentralWidget(self.centralwidget)

        self.retranslateUi(Agenda)
        QtCore.QMetaObject.connectSlotsByName(Agenda)
        Agenda.setTabOrder(self.ln_contato, self.ln_fone)
        Agenda.setTabOrder(self.ln_fone, self.ln_email)
        Agenda.setTabOrder(self.ln_email, self.btn_salvar)
        Agenda.setTabOrder(self.btn_salvar, self.btn_limpar)

    def retranslateUi(self, Agenda):
        _translate = QtCore.QCoreApplication.translate
        Agenda.setWindowTitle(_translate("Agenda", "Agenda"))
        self.label_2.setText(_translate("Agenda", "Nome"))
        self.label_3.setText(_translate("Agenda", "Telefone"))
        self.label_4.setText(_translate("Agenda", "Email"))
        self.btn_buscar.setText(_translate("Agenda", "Buscar"))
        self.btn_salvar.setText(_translate("Agenda", "Salvar"))
        self.btn_deletar.setText(_translate("Agenda", "Deletar"))
        self.btn_limpar.setText(_translate("Agenda", "Limpar"))
        self.label.setText(_translate("Agenda", "Contatos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Agenda = QtWidgets.QMainWindow()
    ui = Ui_Agenda()
    ui.setupUi(Agenda)
    Agenda.show()
    sys.exit(app.exec())
