# Form implementation generated from reading ui file 'agenda.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Agenda(object):
    def setupUi(self, Agenda):
        Agenda.setObjectName("Agenda")
        Agenda.resize(279, 288)
        Agenda.setStyleSheet("background-color: rgb(122, 122, 122);\n"
"color: rgb(6, 6, 6);")
        self.centralwidget = QtWidgets.QWidget(parent=Agenda)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("QLabel{\n"
"    border-radius:5px;\n"
"    background-color: rgb(213, 213, 213);\n"
"    font: 14pt \"Times New Roman\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"    \n"
"    font: 14pt \"Times New Roman\";\n"
"    background-color: rgb(204, 204, 204);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(79, 79, 79);\n"
"    font: 75 15pt \"Times New Roman\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 0, 1, 1)
        self.ln_contato = QtWidgets.QLineEdit(parent=self.frame)
        self.ln_contato.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ln_contato.setObjectName("ln_contato")
        self.gridLayout.addWidget(self.ln_contato, 3, 1, 1, 2)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 70))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 2, 3)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.ln_email = QtWidgets.QLineEdit(parent=self.frame)
        self.ln_email.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ln_email.setObjectName("ln_email")
        self.gridLayout.addWidget(self.ln_email, 7, 1, 1, 2)
        self.ln_fone = QtWidgets.QLineEdit(parent=self.frame)
        self.ln_fone.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ln_fone.setObjectName("ln_fone")
        self.gridLayout.addWidget(self.ln_fone, 5, 1, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.btn_salvar = QtWidgets.QPushButton(parent=self.frame)
        self.btn_salvar.setObjectName("btn_salvar")
        self.gridLayout.addWidget(self.btn_salvar, 10, 1, 1, 1)
        self.btn_limpar = QtWidgets.QPushButton(parent=self.frame)
        self.btn_limpar.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btn_limpar.setObjectName("btn_limpar")
        self.gridLayout.addWidget(self.btn_limpar, 10, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem4, 11, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.frame)
        Agenda.setCentralWidget(self.centralwidget)

        self.retranslateUi(Agenda)
        QtCore.QMetaObject.connectSlotsByName(Agenda)

    def retranslateUi(self, Agenda):
        _translate = QtCore.QCoreApplication.translate
        Agenda.setWindowTitle(_translate("Agenda", "Agenda"))
        self.label.setText(_translate("Agenda", "Agenda Telefònica"))
        self.label_2.setText(_translate("Agenda", "Nome"))
        self.label_3.setText(_translate("Agenda", "Telefone"))
        self.label_4.setText(_translate("Agenda", "Email"))
        self.btn_salvar.setText(_translate("Agenda", "Salvar"))
        self.btn_limpar.setText(_translate("Agenda", "Limpar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Agenda = QtWidgets.QMainWindow()
    ui = Ui_Agenda()
    ui.setupUi(Agenda)
    Agenda.show()
    sys.exit(app.exec())
